/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Ordenacao;
import model.Ordenacao_Thread;
import static view.TelaMenuIdiomas.pais;

/**
 *
 * @author Sam Gatoo
 */
public class TelaCasoTesteThread extends javax.swing.JFrame {

    Ordenacao vetor = new Ordenacao();

    /**
     * Creates new form TelaCasoTeste
     */
    public TelaCasoTesteThread() {
        initComponents();

        switch (pais) {
            case 1: {
                jLabel10.setText("DICIONARIO PORTUGUES");
                break;
            }
            case 2: {
                jLabel10.setText("DICIONARIO INGLES");
                break;
            }
            case 3: {
                jLabel10.setText("DICIONARIO ESPANHOL");
                break;
            }
            default: {
                jLabel10.setText("SELECIONE UM DICIONARIO");
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldResultadoInsertion = new javax.swing.JTextField();
        jTextFieldResultadoSelection = new javax.swing.JTextField();
        jTextFieldResultadoMerge = new javax.swing.JTextField();
        jTextFieldResultadoQuick = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 22)); // NOI18N
        jLabel1.setText("Vamos ver qual o mais rápido      TESTE THREAD SORT");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldResultadoInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoInsertionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Insertion Sort");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Selection Sort");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Merge Sort");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel5.setText("Quick Sort");

        jLabel6.setText("-------------");

        jLabel7.setText("-------");

        jLabel8.setText("-------");

        jLabel9.setText("-----------");

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldResultadoInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldResultadoSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jTextFieldResultadoQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jTextFieldResultadoMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResultadoSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldResultadoInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldResultadoQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldResultadoMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch (pais) {
            case 1: {
                try {
                    //DICIONARIO PORTUGUES
                    long start = System.currentTimeMillis();
                    DicionarioPortugueseBrazilian port = new DicionarioPortugueseBrazilian();
                    port.LerPortugueseBrazilianOrdenado();
                    Ordenacao_Thread tarefaSelection = new Ordenacao_Thread(port.getDicionarioPortugueseBrazilian(), "selectionsort");
                    Thread SelectionSort = new Thread(tarefaSelection);
                    //  SelectionSort.setPriority(Thread.MAX_PRIORITY);
                    SelectionSort.start();
                    port.GravarPortugueseBrazilianOrdenado();
                    SelectionSort.join();
                    long finish = System.currentTimeMillis();
                    float total = finish - start;
                    total = total / 1000;

                    long start2 = System.currentTimeMillis();
                    port.LerPortugueseBrazilianOrdenado();
                    Ordenacao_Thread tarefaInsertion = new Ordenacao_Thread(port.getDicionarioPortugueseBrazilian(), "insertionsort");
                    Thread InsertionSort = new Thread(tarefaInsertion);
                    InsertionSort.start();
                    InsertionSort.join();
                    port.GravarPortugueseBrazilianOrdenado();
                    long finish2 = System.currentTimeMillis();
                    float total2 = finish2 - start2;
                    total2 = total2 / 1000;

                    long start3 = System.currentTimeMillis();
                    port.LerPortugueseBrazilianOrdenado();
                    Ordenacao_Thread tarefaQuickSort = new Ordenacao_Thread(port.getDicionarioPortugueseBrazilian(), "quicksort");
                    Thread QuickSort = new Thread(tarefaQuickSort);
                    QuickSort.start();
                    QuickSort.join();
                    port.setDicionarioPortugueseBrazilian(tarefaQuickSort.getArr());
                    port.GravarPortugueseBrazilianOrdenado();
                    long finish3 = System.currentTimeMillis();
                    float total3 = finish3 - start3;
                    total3 = total3 / 1000;

                    long start4 = System.currentTimeMillis();
                    port.LerPortugueseBrazilianOrdenado();
                    Ordenacao_Thread tarefaMerge = new Ordenacao_Thread(port.getDicionarioPortugueseBrazilian(), "mergesort");
                    Thread MergeSort = new Thread(tarefaMerge);
                    MergeSort.start();
                    MergeSort.join();
                    port.GravarPortugueseBrazilianOrdenado();
                    long finish4 = System.currentTimeMillis();
                    float total4 = finish4 - start4;
                    total4 = total4 / 1000;

                    jTextFieldResultadoSelection.setText("O Selection sort com Thread demorou " + total + " - Segundos");
                    jTextFieldResultadoInsertion.setText("O Insertion sort com Thread demorou " + total2 + " - Segundos");
                    jTextFieldResultadoQuick.setText("O Quick sort com Thread demorou " + total3 + " - Segundos");
                    jTextFieldResultadoMerge.setText("O Merge sort com Thread demorou " + total4 + " - Segundos");
                    break;
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaCasoTesteThread.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            case 2: {
                try {
                    //DICIONARIO INGLÊS
                    long start = System.currentTimeMillis();
                    DicionarioEnglishAmerican eng = new DicionarioEnglishAmerican();
                    eng.LerEnglishAmerican();
                    Ordenacao_Thread tarefaSelection = new Ordenacao_Thread(eng.getDicionarioOriginalEnglishAmerican(), "selectionsort");
                    Thread SelectionSort = new Thread(tarefaSelection);
                    SelectionSort.start();
                    SelectionSort.join();
                    eng.GravarEnglishAmericanOrdenado();
                    long finish = System.currentTimeMillis();
                    float total = finish - start;
                    total = total / 1000;

                    long start2 = System.currentTimeMillis();
                    eng.LerEnglishAmerican();
                    Ordenacao_Thread tarefaInsertion = new Ordenacao_Thread(eng.getDicionarioOriginalEnglishAmerican(), "insertionsort");
                    Thread InsertionSort = new Thread(tarefaInsertion);
                    InsertionSort.start();
                    InsertionSort.join();
                    eng.GravarEnglishAmericanOrdenado();
                    long finish2 = System.currentTimeMillis();
                    float total2 = finish2 - start2;
                    total2 = total2 / 1000;

                    long start3 = System.currentTimeMillis();
                    eng.LerEnglishAmerican();
                    Ordenacao_Thread tarefaQuickSort = new Ordenacao_Thread(eng.getDicionarioOriginalEnglishAmerican(), "quicksort");
                    Thread QuickSort = new Thread(tarefaQuickSort);
                    QuickSort.start();
                    QuickSort.join();
                    eng.setDicionarioOriginalEnglishAmerican(tarefaQuickSort.getArr());
                    eng.GravarEnglishAmericanOrdenado();
                    long finish3 = System.currentTimeMillis();
                    float total3 = finish3 - start3;
                    total3 = total3 / 1000;

                    long start4 = System.currentTimeMillis();
                    eng.LerEnglishAmerican();
                    Ordenacao_Thread tarefaMerge = new Ordenacao_Thread(eng.getDicionarioOriginalEnglishAmerican(), "mergesort");
                    Thread MergeSort = new Thread(tarefaMerge);
                    MergeSort.start();
                    MergeSort.join();
                    eng.GravarEnglishAmericanOrdenado();
                    long finish4 = System.currentTimeMillis();
                    float total4 = finish4 - start4;
                    total4 = total4 / 1000;

                    jTextFieldResultadoSelection.setText("O Selection sort com Thread demorou " + total + " - Segundos");
                    jTextFieldResultadoInsertion.setText("O Insertion sort com Thread demorou " + total2 + " - Segundos");
                    jTextFieldResultadoQuick.setText("O Quick sort com Thread demorou " + total3 + " - Segundos");
                    jTextFieldResultadoMerge.setText("O Merge sort com Thread demorou " + total4 + " - Segundos");

                    break;
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaCasoTesteThread.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            case 3: {
                try {
                    //DICIONARIO ESPANHOL
                    long start = System.currentTimeMillis();
                    DicionarioSpanish span = new DicionarioSpanish();
                    span.LerSpanish();
                    Ordenacao_Thread tarefaSelection = new Ordenacao_Thread(span.getDicionarioOriginalSpanish(), "selectionsort");
                    Thread SelectionSort = new Thread(tarefaSelection);
                    SelectionSort.start();
                    SelectionSort.join();
                    span.GravarSpanishOrdenado();
                    long finish = System.currentTimeMillis();
                    float total = finish - start;
                    total = total / 1000;

                    long start2 = System.currentTimeMillis();
                    span.LerSpanish();
                    Ordenacao_Thread tarefaInsertion = new Ordenacao_Thread(span.getDicionarioOriginalSpanish(), "insertionsort");
                    Thread InsertionSort = new Thread(tarefaInsertion);
                    InsertionSort.start();
                    InsertionSort.join();
                    span.GravarSpanishOrdenado();
                    long finish2 = System.currentTimeMillis();
                    float total2 = finish2 - start2;
                    total2 = total2 / 1000;

                    long start3 = System.currentTimeMillis();
                    span.LerSpanish();
                    Ordenacao_Thread tarefaQuickSort = new Ordenacao_Thread(span.getDicionarioOriginalSpanish(), "quicksort");
                    Thread QuickSort = new Thread(tarefaQuickSort);
                    QuickSort.start();
                    QuickSort.join();
                    span.setDicionarioOriginalSpanish(tarefaQuickSort.getArr());
                    span.GravarSpanishOrdenado();
                    long finish3 = System.currentTimeMillis();
                    float total3 = finish3 - start3;
                    total3 = total3 / 1000;

                    long start4 = System.currentTimeMillis();
                    span.LerSpanish();
                    Ordenacao_Thread tarefaMerge = new Ordenacao_Thread(span.getDicionarioOriginalSpanish(), "mergesort");
                    Thread MergeSort = new Thread(tarefaMerge);
                    MergeSort.start();
                    MergeSort.join();
                    long finish4 = System.currentTimeMillis();
                    float total4 = finish4 - start4;
                    total4 = total4 / 1000;

                    jTextFieldResultadoSelection.setText("O Selection sort com Thread demorou " + total + " - Segundos");
                    jTextFieldResultadoInsertion.setText("O Insertion sort com Thread demorou " + total2 + " - Segundos");
                    jTextFieldResultadoQuick.setText("O Quick sort com Thread demorou " + total3 + " - Segundos");
                    jTextFieldResultadoMerge.setText("O Merge sort com Thread demorou " + total4 + " - Segundos");
                    break;
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaCasoTesteThread.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            default: {

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldResultadoInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoInsertionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoInsertionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaMenuIdiomas nova = new TelaMenuIdiomas();
        this.dispose();
        nova.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCasoTesteThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCasoTesteThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCasoTesteThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCasoTesteThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCasoTesteThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldResultadoInsertion;
    private javax.swing.JTextField jTextFieldResultadoMerge;
    private javax.swing.JTextField jTextFieldResultadoQuick;
    private javax.swing.JTextField jTextFieldResultadoSelection;
    // End of variables declaration//GEN-END:variables

}
