/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Sam Gatoo
 */
public class TelaMenuIdiomas extends javax.swing.JFrame {

    public static int pais = 0;

    /**
     * Creates new form TelaMenuIdiomas
     */
    public TelaMenuIdiomas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEstadosUnidos = new javax.swing.JButton();
        jButtonEspanha = new javax.swing.JButton();
        jButtonBrasil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU IDIOMAS");
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um idioma para comçar");

        jButtonEstadosUnidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UnitedStatesflag_6361.png"))); // NOI18N
        jButtonEstadosUnidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadosUnidosActionPerformed(evt);
            }
        });

        jButtonEspanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spain_flags_flag_17068.png"))); // NOI18N
        jButtonEspanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspanhaActionPerformed(evt);
            }
        });

        jButtonBrasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/brazil_flags_flag_16979.png"))); // NOI18N
        jButtonBrasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonBrasil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEstadosUnidos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonEspanha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEstadosUnidos)
                    .addComponent(jButtonEspanha)
                    .addComponent(jButtonBrasil))
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrasilActionPerformed
        // TODO add your handling code here:
        pais = 1;
        TelaMenuOrdenacaoEBusca nova = new TelaMenuOrdenacaoEBusca();
        this.dispose();
        nova.setVisible(true);
    }//GEN-LAST:event_jButtonBrasilActionPerformed

    private void jButtonEstadosUnidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadosUnidosActionPerformed
        // TODO add your handling code here:
        pais = 2;
        TelaMenuOrdenacaoEBusca nova = new TelaMenuOrdenacaoEBusca();
        this.dispose();
        nova.setVisible(true);
    }//GEN-LAST:event_jButtonEstadosUnidosActionPerformed

    private void jButtonEspanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspanhaActionPerformed
        // TODO add your handling code here:
        pais = 3;
        TelaMenuOrdenacaoEBusca nova = new TelaMenuOrdenacaoEBusca();
        this.dispose();
        nova.setVisible(true);
    }//GEN-LAST:event_jButtonEspanhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuIdiomas().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrasil;
    private javax.swing.JButton jButtonEspanha;
    private javax.swing.JButton jButtonEstadosUnidos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
